package com.example.recyclerviewimpl

data class ItemsDataClass(val id: Int, val name: String, val imgUrl: String)

var itemsDataClassList = arrayListOf(
    ItemsDataClass(
        0,
        "Amir",
        "https://www.gstatic.com/webp/gallery3/1.sm.png"
    ),
    ItemsDataClass(
        1,
        "Amir",
        "https://placebear.com/g/200/200"
    ),
    ItemsDataClass(
        2,
        "Amir",
        "https://via.placeholder.com/300.png/09f/fff"
    ),
    ItemsDataClass(
        3,
        "Amir",
        "https://via.placeholder.com/300.png/09f/fff"
    ),
    ItemsDataClass(
        4,
        "Amir",
        "https://via.placeholder.com/300.png/09f/fff"
    ),
    ItemsDataClass(
        5,
        "Amir",
        "https://via.placeholder.com/300.png/09f/fff"
    ),
    ItemsDataClass(
        6,
        "Amir",
        "https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg"
    ),
    ItemsDataClass(
        7,
        "Amir",
        "https://www.kasandbox.org/programming-images/avatars/spunky-sam.png"
    ),
    ItemsDataClass(
        8,
        "Amir",
        "https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg"
    ),
    ItemsDataClass(
        9,
        "Amir",
        "https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg"
    ),
    ItemsDataClass(
        10,
        "Amir",
        "https://www.kasandbox.org/programming-images/avatars/spunky-sam.png"
    ),
    ItemsDataClass(
        0,
        "Amir",
        "https://www.pakainfo.com/wp-content/uploads/2021/09/image-url-for-testing.jpg"
    ),
    ItemsDataClass(
        0,
        "Amir",
        "https://www.kasandbox.org/programming-images/avatars/spunky-sam.png"
    ),
    ItemsDataClass(
        0,
        "Amir",
        "https://www.kasandbox.org/programming-images/avatars/spunky-sam.png"
    ),
    ItemsDataClass(
        0,
        "Amir",
        "https://www.kasandbox.org/programming-images/avatars/spunky-sam.png"
    )
)